# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be738ec05ab04b796475fe9a7e43015af844712be03b5c3443e3a2719691caa107141fb54693779a35eab0d241d5c9f70b59e36a161f3e0d250afa212c88f436

test:
  secret_key_base: d3c351031578993f16ae17f3adc309ec616078f3dccc112541525586b3275b67959b56cdf1039dcf3f9a2b92f251e05f4f692032c4feb18ac881bf031ffc6999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
